package jun.ssm.mapper;

import java.util.List;
import jun.ssm.po.TCustomer2;
import jun.ssm.po.TCustomer2Example;
import org.apache.ibatis.annotations.Param;

public interface TCustomer2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    long countByExample(TCustomer2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int deleteByExample(TCustomer2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int insert(TCustomer2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int insertSelective(TCustomer2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    List<TCustomer2> selectByExample(TCustomer2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    TCustomer2 selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") TCustomer2 record, @Param("example") TCustomer2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByExample(@Param("record") TCustomer2 record, @Param("example") TCustomer2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByPrimaryKeySelective(TCustomer2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_customer2
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByPrimaryKey(TCustomer2 record);
}