package jun.ssm.mapper;

import java.util.List;
import jun.ssm.po.TDict;
import jun.ssm.po.TDictExample;
import org.apache.ibatis.annotations.Param;

public interface TDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    long countByExample(TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int deleteByExample(TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int deleteByPrimaryKey(String did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int insert(TDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int insertSelective(TDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    List<TDict> selectByExample(TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    TDict selectByPrimaryKey(String did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") TDict record, @Param("example") TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByExample(@Param("record") TDict record, @Param("example") TDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByPrimaryKeySelective(TDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dict
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByPrimaryKey(TDict record);
}