package jun.ssm.mapper;

import java.util.List;
import jun.ssm.po.TVisit;
import jun.ssm.po.TVisitExample;
import org.apache.ibatis.annotations.Param;

public interface TVisitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    long countByExample(TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int deleteByExample(TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int deleteByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int insert(TVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int insertSelective(TVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    List<TVisit> selectByExample(TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    TVisit selectByPrimaryKey(Integer vid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") TVisit record, @Param("example") TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByExample(@Param("record") TVisit record, @Param("example") TVisitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByPrimaryKeySelective(TVisit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_visit
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    int updateByPrimaryKey(TVisit record);
}