package jun.ssm.po;

public class TCustomer2 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer2.cid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer2.custName
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private String custname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer2.custSource
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private String custsource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer2.custPhone
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private String custphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer2.custMobile
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private String custmobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_customer2.custLevel
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private String custlevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer2.cid
     *
     * @return the value of t_customer2.cid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer2.cid
     *
     * @param cid the value for t_customer2.cid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer2.custName
     *
     * @return the value of t_customer2.custName
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer2.custName
     *
     * @param custname the value for t_customer2.custName
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer2.custSource
     *
     * @return the value of t_customer2.custSource
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getCustsource() {
        return custsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer2.custSource
     *
     * @param custsource the value for t_customer2.custSource
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setCustsource(String custsource) {
        this.custsource = custsource == null ? null : custsource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer2.custPhone
     *
     * @return the value of t_customer2.custPhone
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getCustphone() {
        return custphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer2.custPhone
     *
     * @param custphone the value for t_customer2.custPhone
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setCustphone(String custphone) {
        this.custphone = custphone == null ? null : custphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer2.custMobile
     *
     * @return the value of t_customer2.custMobile
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getCustmobile() {
        return custmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer2.custMobile
     *
     * @param custmobile the value for t_customer2.custMobile
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setCustmobile(String custmobile) {
        this.custmobile = custmobile == null ? null : custmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_customer2.custLevel
     *
     * @return the value of t_customer2.custLevel
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getCustlevel() {
        return custlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_customer2.custLevel
     *
     * @param custlevel the value for t_customer2.custLevel
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setCustlevel(String custlevel) {
        this.custlevel = custlevel == null ? null : custlevel.trim();
    }
}