package jun.ssm.po;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class TLinkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_linkman.linkId
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private Integer linkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_linkman.lkmName
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    @Size(min=1,max=30,message="{linkman.lkmname.length.error}")
    private String lkmname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_linkman.lkmGender
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private String lkmgender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_linkman.lkmPhone
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    @NotNull(message="{linkman.lkmphone.isempty}")
    private String lkmphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_linkman.lkmMobile
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private String lkmmobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_linkman.clid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private Integer clid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_linkman.linkId
     *
     * @return the value of t_linkman.linkId
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public Integer getLinkid() {
        return linkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_linkman.linkId
     *
     * @param linkid the value for t_linkman.linkId
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setLinkid(Integer linkid) {
        this.linkid = linkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_linkman.lkmName
     *
     * @return the value of t_linkman.lkmName
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getLkmname() {
        return lkmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_linkman.lkmName
     *
     * @param lkmname the value for t_linkman.lkmName
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setLkmname(String lkmname) {
        this.lkmname = lkmname == null ? null : lkmname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_linkman.lkmGender
     *
     * @return the value of t_linkman.lkmGender
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getLkmgender() {
        return lkmgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_linkman.lkmGender
     *
     * @param lkmgender the value for t_linkman.lkmGender
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setLkmgender(String lkmgender) {
        this.lkmgender = lkmgender == null ? null : lkmgender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_linkman.lkmPhone
     *
     * @return the value of t_linkman.lkmPhone
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getLkmphone() {
        return lkmphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_linkman.lkmPhone
     *
     * @param lkmphone the value for t_linkman.lkmPhone
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setLkmphone(String lkmphone) {
        this.lkmphone = lkmphone == null ? null : lkmphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_linkman.lkmMobile
     *
     * @return the value of t_linkman.lkmMobile
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getLkmmobile() {
        return lkmmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_linkman.lkmMobile
     *
     * @param lkmmobile the value for t_linkman.lkmMobile
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setLkmmobile(String lkmmobile) {
        this.lkmmobile = lkmmobile == null ? null : lkmmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_linkman.clid
     *
     * @return the value of t_linkman.clid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public Integer getClid() {
        return clid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_linkman.clid
     *
     * @param clid the value for t_linkman.clid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setClid(Integer clid) {
        this.clid = clid;
    }
}