package jun.ssm.po;

import java.util.ArrayList;
import java.util.List;

public class TLinkmanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public TLinkmanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLinkidIsNull() {
            addCriterion("linkId is null");
            return (Criteria) this;
        }

        public Criteria andLinkidIsNotNull() {
            addCriterion("linkId is not null");
            return (Criteria) this;
        }

        public Criteria andLinkidEqualTo(Integer value) {
            addCriterion("linkId =", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidNotEqualTo(Integer value) {
            addCriterion("linkId <>", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidGreaterThan(Integer value) {
            addCriterion("linkId >", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidGreaterThanOrEqualTo(Integer value) {
            addCriterion("linkId >=", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidLessThan(Integer value) {
            addCriterion("linkId <", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidLessThanOrEqualTo(Integer value) {
            addCriterion("linkId <=", value, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidIn(List<Integer> values) {
            addCriterion("linkId in", values, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidNotIn(List<Integer> values) {
            addCriterion("linkId not in", values, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidBetween(Integer value1, Integer value2) {
            addCriterion("linkId between", value1, value2, "linkid");
            return (Criteria) this;
        }

        public Criteria andLinkidNotBetween(Integer value1, Integer value2) {
            addCriterion("linkId not between", value1, value2, "linkid");
            return (Criteria) this;
        }

        public Criteria andLkmnameIsNull() {
            addCriterion("lkmName is null");
            return (Criteria) this;
        }

        public Criteria andLkmnameIsNotNull() {
            addCriterion("lkmName is not null");
            return (Criteria) this;
        }

        public Criteria andLkmnameEqualTo(String value) {
            addCriterion("lkmName =", value, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameNotEqualTo(String value) {
            addCriterion("lkmName <>", value, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameGreaterThan(String value) {
            addCriterion("lkmName >", value, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameGreaterThanOrEqualTo(String value) {
            addCriterion("lkmName >=", value, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameLessThan(String value) {
            addCriterion("lkmName <", value, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameLessThanOrEqualTo(String value) {
            addCriterion("lkmName <=", value, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameLike(String value) {
            addCriterion("lkmName like", value, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameNotLike(String value) {
            addCriterion("lkmName not like", value, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameIn(List<String> values) {
            addCriterion("lkmName in", values, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameNotIn(List<String> values) {
            addCriterion("lkmName not in", values, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameBetween(String value1, String value2) {
            addCriterion("lkmName between", value1, value2, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmnameNotBetween(String value1, String value2) {
            addCriterion("lkmName not between", value1, value2, "lkmname");
            return (Criteria) this;
        }

        public Criteria andLkmgenderIsNull() {
            addCriterion("lkmGender is null");
            return (Criteria) this;
        }

        public Criteria andLkmgenderIsNotNull() {
            addCriterion("lkmGender is not null");
            return (Criteria) this;
        }

        public Criteria andLkmgenderEqualTo(String value) {
            addCriterion("lkmGender =", value, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderNotEqualTo(String value) {
            addCriterion("lkmGender <>", value, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderGreaterThan(String value) {
            addCriterion("lkmGender >", value, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderGreaterThanOrEqualTo(String value) {
            addCriterion("lkmGender >=", value, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderLessThan(String value) {
            addCriterion("lkmGender <", value, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderLessThanOrEqualTo(String value) {
            addCriterion("lkmGender <=", value, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderLike(String value) {
            addCriterion("lkmGender like", value, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderNotLike(String value) {
            addCriterion("lkmGender not like", value, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderIn(List<String> values) {
            addCriterion("lkmGender in", values, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderNotIn(List<String> values) {
            addCriterion("lkmGender not in", values, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderBetween(String value1, String value2) {
            addCriterion("lkmGender between", value1, value2, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmgenderNotBetween(String value1, String value2) {
            addCriterion("lkmGender not between", value1, value2, "lkmgender");
            return (Criteria) this;
        }

        public Criteria andLkmphoneIsNull() {
            addCriterion("lkmPhone is null");
            return (Criteria) this;
        }

        public Criteria andLkmphoneIsNotNull() {
            addCriterion("lkmPhone is not null");
            return (Criteria) this;
        }

        public Criteria andLkmphoneEqualTo(String value) {
            addCriterion("lkmPhone =", value, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneNotEqualTo(String value) {
            addCriterion("lkmPhone <>", value, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneGreaterThan(String value) {
            addCriterion("lkmPhone >", value, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneGreaterThanOrEqualTo(String value) {
            addCriterion("lkmPhone >=", value, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneLessThan(String value) {
            addCriterion("lkmPhone <", value, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneLessThanOrEqualTo(String value) {
            addCriterion("lkmPhone <=", value, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneLike(String value) {
            addCriterion("lkmPhone like", value, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneNotLike(String value) {
            addCriterion("lkmPhone not like", value, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneIn(List<String> values) {
            addCriterion("lkmPhone in", values, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneNotIn(List<String> values) {
            addCriterion("lkmPhone not in", values, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneBetween(String value1, String value2) {
            addCriterion("lkmPhone between", value1, value2, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmphoneNotBetween(String value1, String value2) {
            addCriterion("lkmPhone not between", value1, value2, "lkmphone");
            return (Criteria) this;
        }

        public Criteria andLkmmobileIsNull() {
            addCriterion("lkmMobile is null");
            return (Criteria) this;
        }

        public Criteria andLkmmobileIsNotNull() {
            addCriterion("lkmMobile is not null");
            return (Criteria) this;
        }

        public Criteria andLkmmobileEqualTo(String value) {
            addCriterion("lkmMobile =", value, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileNotEqualTo(String value) {
            addCriterion("lkmMobile <>", value, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileGreaterThan(String value) {
            addCriterion("lkmMobile >", value, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileGreaterThanOrEqualTo(String value) {
            addCriterion("lkmMobile >=", value, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileLessThan(String value) {
            addCriterion("lkmMobile <", value, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileLessThanOrEqualTo(String value) {
            addCriterion("lkmMobile <=", value, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileLike(String value) {
            addCriterion("lkmMobile like", value, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileNotLike(String value) {
            addCriterion("lkmMobile not like", value, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileIn(List<String> values) {
            addCriterion("lkmMobile in", values, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileNotIn(List<String> values) {
            addCriterion("lkmMobile not in", values, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileBetween(String value1, String value2) {
            addCriterion("lkmMobile between", value1, value2, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andLkmmobileNotBetween(String value1, String value2) {
            addCriterion("lkmMobile not between", value1, value2, "lkmmobile");
            return (Criteria) this;
        }

        public Criteria andClidIsNull() {
            addCriterion("clid is null");
            return (Criteria) this;
        }

        public Criteria andClidIsNotNull() {
            addCriterion("clid is not null");
            return (Criteria) this;
        }

        public Criteria andClidEqualTo(Integer value) {
            addCriterion("clid =", value, "clid");
            return (Criteria) this;
        }

        public Criteria andClidNotEqualTo(Integer value) {
            addCriterion("clid <>", value, "clid");
            return (Criteria) this;
        }

        public Criteria andClidGreaterThan(Integer value) {
            addCriterion("clid >", value, "clid");
            return (Criteria) this;
        }

        public Criteria andClidGreaterThanOrEqualTo(Integer value) {
            addCriterion("clid >=", value, "clid");
            return (Criteria) this;
        }

        public Criteria andClidLessThan(Integer value) {
            addCriterion("clid <", value, "clid");
            return (Criteria) this;
        }

        public Criteria andClidLessThanOrEqualTo(Integer value) {
            addCriterion("clid <=", value, "clid");
            return (Criteria) this;
        }

        public Criteria andClidIn(List<Integer> values) {
            addCriterion("clid in", values, "clid");
            return (Criteria) this;
        }

        public Criteria andClidNotIn(List<Integer> values) {
            addCriterion("clid not in", values, "clid");
            return (Criteria) this;
        }

        public Criteria andClidBetween(Integer value1, Integer value2) {
            addCriterion("clid between", value1, value2, "clid");
            return (Criteria) this;
        }

        public Criteria andClidNotBetween(Integer value1, Integer value2) {
            addCriterion("clid not between", value1, value2, "clid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_linkman
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 13 14:20:45 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_linkman
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}