package jun.ssm.po;

public class TVisit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.vid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.vaddress
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private String vaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.vcontent
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private String vcontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.uvid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private Integer uvid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_visit.cvid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    private Integer cvid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.vid
     *
     * @return the value of t_visit.vid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.vid
     *
     * @param vid the value for t_visit.vid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.vaddress
     *
     * @return the value of t_visit.vaddress
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getVaddress() {
        return vaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.vaddress
     *
     * @param vaddress the value for t_visit.vaddress
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setVaddress(String vaddress) {
        this.vaddress = vaddress == null ? null : vaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.vcontent
     *
     * @return the value of t_visit.vcontent
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public String getVcontent() {
        return vcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.vcontent
     *
     * @param vcontent the value for t_visit.vcontent
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setVcontent(String vcontent) {
        this.vcontent = vcontent == null ? null : vcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.uvid
     *
     * @return the value of t_visit.uvid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public Integer getUvid() {
        return uvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.uvid
     *
     * @param uvid the value for t_visit.uvid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setUvid(Integer uvid) {
        this.uvid = uvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_visit.cvid
     *
     * @return the value of t_visit.cvid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public Integer getCvid() {
        return cvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_visit.cvid
     *
     * @param cvid the value for t_visit.cvid
     *
     * @mbg.generated Thu Jul 13 14:20:45 CST 2017
     */
    public void setCvid(Integer cvid) {
        this.cvid = cvid;
    }
}